.PHONY: clean All

All:
	@echo "----------Building project:[ projettut2 - Debug ]----------"
	@cd "projettut2" && "$(MAKE)" -f  "projettut2.mk"
clean:
	@echo "----------Cleaning project:[ projettut2 - Debug ]----------"
	@cd "projettut2" && "$(MAKE)" -f  "projettut2.mk" clean
